# Generated by Django 4.0.4 on 2022-04-14 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Must be less than 250 characters', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_of_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of publication')),
                ('slug', models.SlugField(unique_for_date='date_of_publication', verbose_name='Slug')),
                ('main_page', models.BooleanField(default=False, help_text='Show on main page', verbose_name='Main')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_of_publication'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Must be less than 250 characters', max_length=250, verbose_name='Category')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category for article',
                'verbose_name_plural': 'Categories for articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Image')),
                ('title', models.CharField(help_text='Must be less than 250 characters', max_length=250, verbose_name='Title')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Image for article',
                'verbose_name_plural': 'Images for article',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.category', verbose_name='Category'),
        ),
    ]
